### ISSUE TITLE
API data is weird and idk how to parse

### ISSUE THREAD

**Issue by Huwng** [Huwng/cobruhvid#1]

**Comment by vn-vna** [comment]
Can you provide more infomation?

**Comment by Huwng** [comment]
I have an API that give me like an array of JSON objects (I believe), I can log that to console fine, but when i try to get it into a function to parse, all the data is gone.
Some people have told me to use regex, but I don't really know how to implement that since I'm fairly new to JS developing

**Comment by vn-vna** [comment]
Checkout its format
